[project]
name = "sftp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "gnureadline>=8.2.13",
    "paramiko>=3.5.1",
    "pydantic>=2.11.5",
    "typer>=0.16.0",
]
